def prefix_version = ""

pipeline {
	
	environment {
        artifactoryip="192.168.217.52:8081"
	}
	
agent { label 'AS400_DEV_1' }

    stages {
	
		stage('Build') {

            steps {
                echo "###############################################################################################"
				echo "#                                  BUILD GS                                                   #"
				echo "###############################################################################################"
				
				sh 'cd $WORKSPACE/src/ghostscript-9.50 && ./configure && gmake'
				
				}
        }	

		stage('Deploy') {

            steps {
				echo "###############################################################################################"
				echo "#                                          DEPLOY                                             #"
				echo "###############################################################################################"

				script {
					def version = readFile("${WORKSPACE}//version.txt").trim()
					sh "cd $WORKSPACE/src/ghostscript-9.50/bin && zip gs.zip gs"
					
					sh "curl -ujenkins:Mapping1234\$ -T \"${WORKSPACE}/src/ghostscript-9.50/bin/gs.zip\" \"http://${artifactoryip}/artifactory/Opale/Dependencies/IBMi/mapping-ghostscript-pase-${version}.zip\""
				}
			}
		}		
	}
}
